services:
  api-gateway:
    image: mukhtarovich/api-gateway:latest
    container_name: api-gateway
    restart: always
    depends_on:
      - auth-service
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://host.docker.internal:8082

  auth-service:
    image: mukhtarovich/auth-service:latest
    container_name: auth-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      TELEGRAM_TOKEN: AAGyOQAAod-L3G4ZLogfAiZUQutCgRa5-cJnIg3LT0TZWg

  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: