spring.application.name=Auth-Service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/auth
spring.datasource.username=${DATABASE_NAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
server.port=8082
server.servlet.context-path=/api/v1

telegram.token= ${TELEGRAM_TOKEN:AAGyOQAAod-L3G4ZLogfAiZUQutCgRa5-cJnIg3LT0TZWg}