spring.application.name=Auth-Service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
server.port=8080
server.servlet.context-path=/api/v1

spring.security.user.name=mukhtarovich
spring.security.user.password=dilbekk070
spring.security.user.roles=admin
spring.security.oauth2.client.registration.google.client-id=